### ISSUE TITLE
Connection over IPv6 possible?

### ISSUE THREAD

**Issue by KonradHoeffner** [srdc/virt-jena#2]
When I try connecting to my server with the statement below (address removed), I get a Jena exception (see at the bottom).  Unfortunately, the exception is not very detailed, so I am wondering, is it possible to connect over IPv6? If yes, how can I debug this issue?

```
VirtGraph graph = new virtGraph("jdbc:virtuoso://[$MY_IP_6_ADRESS]:1111",
            PropertiesLoader.virtuosoUser,PropertiesLoader.virtuosoPassword);

com.hp.hpl.jena.shared.JenaException: virtuoso.jdbc4.VirtuosoException: Connection failed: 119]
at virtuoso.jena.driver.VirtGraph.<init>(VirtGraph.java:182)
at virtuoso.jena.driver.VirtGraph.<init>(VirtGraph.java:103)
at org.aksw.linkedspending.upload.UploadWorker.uploadDataSet(UploadWorker.java:21)
at org.aksw.linkedspending.upload.UploadWorkerTest.testUploadDataSet(UploadWorkerTest.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: virtuoso.jdbc4.VirtuosoException: Connection failed: 119]
at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
at virtuoso.jdbc4.VirtuosoConnection.connect(Unknown Source)
at virtuoso.jdbc4.VirtuosoConnection.<init>(Unknown Source)
at virtuoso.jdbc4.Driver.connect(Unknown Source)
at java.sql.DriverManager.getConnection(DriverManager.java:664)
at java.sql.DriverManager.getConnection(DriverManager.java:247)
at virtuoso.jena.driver.VirtGraph.<init>(VirtGraph.java:165)
... 26 more
```

**Comment by sinaci** [comment]
Sorry for answering this late, but we have not overriden the network
communication of the default virt-jena adapter. I suppose it does not
support ipv6.

Anil
